# Generated by Django 3.2.4 on 2021-09-03 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecom', '0004_mycart_orders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='status',
        ),
    ]
